### ISSUE TITLE
Find a spot for the latest blog post on dlang.org

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#10]
In theory the D Blog would belong to "News", but that's already quite full:

![image](https://cloud.githubusercontent.com/assets/4370550/16064529/709050ce-32a2-11e6-9a0e-f19ee92498a7.png)

I talked with @CyberShadow recently and he suggested that when the official Twitter account is used it will be displayed on dlang.org. I think this is a good idea (see #7), however `#dlang` gets used more and more, s.t. the announcement might not be visible for long and there are also people who block such widgets.

What about updating the first sentence of "News" on a new blog release? (maybe manually until we find a good automation)

**Comment by mdparker** [comment]
As it stands, the latest posts are also getting announced in the forums, and those posts show up on the front page in the Latest Announcements section. As long as I make it clear it's from the D Blog in the title, that should do.

That said, one approach to doing this would be to embed some sort of RSS widget on the front page, showing the most recent blog posts. However it's done, it's an issue for the website rather than here.
