### ISSUE TITLE
Add feedback + submit content links 

### ISSUE THREAD

**Issue by wilzbach** [dlang/D-Blog-Theme#13]
If we want to ensure that we keep having great content, it could be beneficial to link to this repo for improvement ideas and also provide information on how to contribute content.

**Comment by mdparker** [comment]
General feedback should probably go to the forums rather than here. I'll add a link in the side bar to the general forums for that and also a link here for reporting issues specific to the theme.

Right now, I'm not open to the idea of accepting content submissions. The blog has very specific goals and I want to work within those parameters for the time being. For now, the post schedule is only going to be once or twice per week. I don't expect to have a shortage of content any time soon.

**Comment by mdparker** [comment]
OK, I've added two links to the sidebar: one to the General forum for discussion and one here for reporting issues. Somewhere down the road I'll revisit the idea of calling for content.

Thanks for all the suggestions you've made so far @wilzbach !
